version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 99
  reviewers:
  - omjadas
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 99
